#!/usr/bin/ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

pod 'ReactiveCocoa'
pod 'AFNetworking'
pod 'MagicalRecord'
pod 'PureLayout'
pod 'NSString+Ruby'
pod 'NSURL+QueryDictionary'
pod 'UIColor-Utilities'
pod 'UIView+Positioning'
pod 'CLKSingletons'
